import { SquareLocation } from "../types";

export const SQUARES_NUMBER = 9;
export const SQUARE_NOT_FOUND = -1;

export const ROWS_OF_SQUARES = [
  [SquareLocation.TopLeft, SquareLocation.TopCenter, SquareLocation.TopRight],
  [
    SquareLocation.MiddleLeft,
    SquareLocation.MiddleCenter,
    SquareLocation.MiddleRight,
  ],
  [
    SquareLocation.BottomLeft,
    SquareLocation.BottomCenter,
    SquareLocation.BottomRight,
  ],
  [
    SquareLocation.TopLeft,
    SquareLocation.MiddleLeft,
    SquareLocation.BottomLeft,
  ],
  [
    SquareLocation.TopCenter,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomCenter,
  ],
  [
    SquareLocation.TopRight,
    SquareLocation.MiddleRight,
    SquareLocation.BottomRight,
  ],
  [
    SquareLocation.TopLeft,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomRight,
  ],
  [
    SquareLocation.TopRight,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomLeft,
  ],
];

export const ROWS_OF_SQUARES_DOUBLE = [
  [
    SquareLocation.TopLeft,
    SquareLocation.TopCenter,
    SquareLocation.TopRight,
    SquareLocation.MiddleLeft,
    SquareLocation.BottomLeft,
  ],
  [
    SquareLocation.TopLeft,
    SquareLocation.TopCenter,
    SquareLocation.TopRight,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomRight,
  ],
  [
    SquareLocation.TopLeft,
    SquareLocation.MiddleLeft,
    SquareLocation.BottomLeft,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomRight,
  ],
  [
    SquareLocation.TopRight,
    SquareLocation.TopLeft,
    SquareLocation.TopCenter,
    SquareLocation.MiddleRight,
    SquareLocation.BottomRight,
  ],
  [
    SquareLocation.TopRight,
    SquareLocation.TopLeft,
    SquareLocation.TopCenter,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomLeft,
  ],
  [
    SquareLocation.TopRight,
    SquareLocation.MiddleRight,
    SquareLocation.BottomRight,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomLeft,
  ],
  [
    SquareLocation.BottomLeft,
    SquareLocation.TopLeft,
    SquareLocation.MiddleLeft,
    SquareLocation.BottomCenter,
    SquareLocation.BottomRight,
  ],
  [
    SquareLocation.BottomLeft,
    SquareLocation.TopLeft,
    SquareLocation.MiddleLeft,
    SquareLocation.TopRight,
    SquareLocation.MiddleCenter,
  ],
  [
    SquareLocation.BottomLeft,
    SquareLocation.TopRight,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomCenter,
    SquareLocation.BottomRight,
  ],
  [
    SquareLocation.BottomRight,
    SquareLocation.BottomLeft,
    SquareLocation.BottomCenter,
    SquareLocation.TopRight,
    SquareLocation.MiddleRight,
  ],
  [
    SquareLocation.BottomRight,
    SquareLocation.BottomLeft,
    SquareLocation.BottomCenter,
    SquareLocation.TopLeft,
    SquareLocation.MiddleCenter,
  ],
  [
    SquareLocation.BottomRight,
    SquareLocation.TopRight,
    SquareLocation.MiddleRight,
    SquareLocation.TopLeft,
    SquareLocation.MiddleCenter,
  ],
  [
    SquareLocation.TopCenter,
    SquareLocation.TopLeft,
    SquareLocation.TopRight,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomCenter,
  ],
  [
    SquareLocation.MiddleLeft,
    SquareLocation.TopLeft,
    SquareLocation.BottomLeft,
    SquareLocation.MiddleCenter,
    SquareLocation.MiddleRight,
  ],
  [
    SquareLocation.MiddleRight,
    SquareLocation.TopRight,
    SquareLocation.BottomRight,
    SquareLocation.MiddleLeft,
    SquareLocation.MiddleCenter,
  ],
  [
    SquareLocation.BottomCenter,
    SquareLocation.TopCenter,
    SquareLocation.MiddleCenter,
    SquareLocation.BottomLeft,
    SquareLocation.BottomRight,
  ],
];
